### ISSUE TITLE
Anzeige von Kontaktdaten in der Map

### ISSUE THREAD

**Issue by ruebezahl** [freifunkMUC/ffmap#1]
Anzeige der Kontaktinformation aus dem Alfred in der Map

**Comment by dl1com** [comment]
Um dies zu erreichen muss zuerst https://github.com/freifunkMUC/ffmap-backend/issues/6 erledigt werden, da atm keine Kontaktdaten in der nodes.json sind die man anzeigen koennte.

**Comment by dl1com** [comment]
done in 549851348509afa0c3757cabfb3c3b0f43f5e12e
