### ISSUE TITLE
Statistiken für das neue Netz anzeigen

### ISSUE THREAD

**Issue by ruebezahl** [freifunkMUC/ffmap#3]
Derzeit werden Stats in der Map vom Testnetz aus dem alten Munin-Daten angezeigt

**Comment by dl1com** [comment]
Die Statistiken werden zZt. von einem dedizierten Server erstellt, der sich die Daten von map.freifunk-muenchen.de/nodes.json holt.
Wenn wir am Montag die Domain die Domain map.freifunk-muenchen.de auf die Karte des neuen Netzes umleiten (aktuell testmap.ffmuc.net), werden automatisch die "richtigen Daten" (also dies des neuen Netzes) fuer die Statistiken verwenden.

Die map des alten Netzes (ab Montag dann nur noch ueber srv01.ffmuc.net zu erreichen) zeigt dann umgekehrt eben die Stats des neuen Netzes an, aber das kann man dann ja einfach komplett rausnehmen.

tl;dr: Der issue loest sich selbststaendig, wenn die Map des neuen Netzes unter map.freifunk-muenchen.de erreichbar ist.

**Comment by dl1com** [comment]
Mir ist aufgefallen dass im neuen Netz doch noch etwas fehlt, und zwar die Generierung der nodes_load.json aus der Alfred Page 159 (benötigt für die node Detail stats). 
Bitte einen crontab dafür ins ffmap backend puppet dafür einbauen, genauer Aufruf siehe readme im backend Repo.

**Comment by spoonicorn** [comment]
nodes_load.json funktioniert nun

**Comment by spoonicorn** [comment]
hab dich assigned ruebezahl, weil du dann DNS technisch tätig werden musst nach der Umstellung. Ansonsten ist das Ticket eh "erledigt"

**Comment by dl1com** [comment]
@spoonicorn die http://testmap.ffmuc.net/nodes_load.json die man da aktuell abrufen kann hat nicht den inhalt den ich von einer nodes_load.json kenne und erwarte...die sieht eher nach einer umbenannten nodes.json aus.

Die nodes_load.json wird folgendermassen erstellt:
0-59/5 \* \* \* \* alfred-json -r 159 -f json -z > /var/www/ffmap/nodes_load.json
Pls fix.

**Comment by spoonicorn** [comment]
Copy & paste fehler. Hab kurz die URL gefixt, nun sollte es passen.

**Comment by saerdnaer** [comment]
@spoonicorn Kann man das Ticket schließen?

**Comment by spoonicorn** [comment]
Ist nur noch offen wegen den Statistiken (ich weiß nicht genau um welche es da ging) die mittlerweile bereits umgeschaltet sein sollten, also wenn das passt, kann man es schließen

**Comment by saerdnaer** [comment]
@ruebezahl @chris007de passt inzwischen alles?

**Comment by dl1com** [comment]
Passt erstmal.
