### ISSUE TITLE
Clients werden in der Liste doppelt gezaehlt

### ISSUE THREAD

**Issue by andz82** [freifunkMUC/ffmap#4]
Aufgrund der noch Uebersichltichkeit der Karte im neuen Netz gerade herausgefunden: in der Liste werden die Clients pro Node genau doppelt gezaehlt wie in wirklichkeit vorhanden, im Graph stimmt die Anzahl.

In der nodes.json gaebe es eigentlich ein Feld "clientcount" pro Knoten, das jedoch durchgaengig auf '0' steht, wohl ein Fehler im ffmap-backend, wohl auch, weil das ueber alfred 158 gar nicht mitgeteilt wird atm.

Das ffmap Frontend berechnet die Anzahl der Clients, indem es die einzelnen Links pro Knoten im nodes.json zaehlt (und das wohl nicht ganz richtig).

Auf der Alfred-Page 159 (also dadurch auch in der nodes_load.json) stimmt die Anzahl, dadurch stimmen die Client Graphen (die werden aus der nodes_load.json generiert).

Stabilste/Langfristige Loesung waere wohl, die Anzahl auch noch ueber die 158 zu versenden, dann kann man das in die clientcount packen und hat die Zahl ohne Rechnerei in der ffmap - waere halt noch eine gluon Anpassung vonnoeten (in der /lib/gluon/announce/collect.lua nodeinfo auch noch die daten aus statistics.d/clients mitverpacken)

**Comment by spoonicorn** [comment]
ich habe die funktion im backend angepasst. Zum einen werden clients nun überhaupt gezählt (clientcount) und sie werden nur einmal gezählt (etwas unhübsch mit einer duplicate list, aber ursachenforschung in ffmap -> viel spass).

Längerfristig können wir uns eh überlegen den ganzen ffmap foobar etwas aufzuräumen. Da würd ich mir aber gern vorher den master ansehen u. mit anderen communities sprechen. Nicht dass 5 ihr eigenes Süppchen kochen.
